services:
  service-pg:
    image: bitnami/postgresql
    ports:
      - '5432:5432'
      # - '5433:5432' usar caso aponte que a porta 5432 já está em uso
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=connect

  service-redis:
    image: bitnami/redis
    ports:
      # - '6379:6379'
      - '6380:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes